### ISSUE TITLE
Copyright notice/license in the header-file

### ISSUE THREAD

**Issue by jozip** [mortie/snow#15]
I'm sure I'm not the only one using Snow by dropping the header-file into the source folder of my projects rather than vendoring the repo. Having the copyright notice along with the license in the file itself may be a good idea.

**Comment by mortie** [comment]
To be honest, I find the whole world of licenses/copyright/IP/lawyers kind of confusing and scary. Does this look okay? https://github.com/mortie/snow/commit/ecaa073460d70ab7b52462908cb4e987df6e3d48 - I made the license say "Copyright 2018 Martin Dørum and Snow contributors" instead of just "Copyright 2018 Martin Dørum", added hard line breaks, and copied the content of the LICENSE file to `snow.h`.

**Comment by jozip** [comment]
It was mostly a matter of making sure that the correct copyright information is in the correct place. (Felt kinda dodgy inserting it myself.)
The header looks excellent. Personally, for my contributions, I claim no copyright. For all intents and purposes -- for whatever it's worth -- it's yours.
That said, I'm a bit wary of adding the "and Snow contributors"-part, as I'm pretty sure it makes things a lot more complicated if push comes to shove. (FYI, IANAL, and whatever I say is purestrain guessing.) You are the creator, principal developer and maintainer, and therefore I'd say that you are the sole copyright holder too.

**Comment by mortie** [comment]
I think you're right, and I've discussed with some others. I removed that "and Snow contributors" part.

https://github.com/mortie/snow/blob/master/snow/snow.h is now live with a license header. I also included a link back to this repository.

**Comment by jozip** [comment]
Great!
