### ISSUE TITLE
First test in a set is always reporting longer times

### ISSUE THREAD

**Issue by jozip** [mortie/snow#16]
Whenever I run a set of tests for a routine, the first one is always taking way longer to complete than the subsequent ones. Now I can't imagine it being anything else than cache issue. (Although I made sure by checking the distance in instructions between the start- and stop-calls to gettimeofday. Can't be too certain with so much dark preprocessor magic around!)

The question is what to make of it. Perhaps it's not even an issue?

**Comment by mortie** [comment]
The relevant code in the `test`/`it` macro looks like this:

```
gettimeofday(&_snow_timer, NULL); \
__VA_ARGS__ \
_snow_successes += 1; \
_snow_print_success(); \
```

That `__VA_ARGS__` expands to the block you pass as a test case, and that `_snow_print_success` first prints the "✓ Success: <description>" line, and then calls `gettimeofday` again to get the time difference. Moving the `gettimeofday` call to before printing doesn't seem to make any diference. I don't think there can be anything wrong with how Snow measures the time a test takes, or how it runs the tests.

Maybe it's caching, or maybe it's the CPU taking a few milliseconds changing from a low frequency from being mostly idle to a high frequency to do work, or maybe something decides to allocate memory (the first time your test suite ever calls `defer`, it will allocate space for 16 pointers to labels, so 128 bytes; after that, it will probably never allocate for `defer`s again unless you have a test case with >16 `defer`s This effect will be bigger when running with valgrind, because of how much slower it makes allocating memory.). Maybe the CPU's branch prediction mispredicts the first few branches somewhere before learning what branch is usually taken. All in all, there's a ton of complexity in both the software and hardware which together might explain why the software seems to start slow-ish and get faster over time :p

If you're experiencing more than a few milliseconds of difference though (i.e if it's an actual issue and not just a curiosity), please post the code where you're using, and I'll give it a test. Here's the code I used:

```
#include <snow/snow.h>

describe(set1, {
	test("a", {
		int count = 0;
		for (int i = 0; i < 1000000; ++i)
			count += 1;
		asserteq(count, 1000000);
	});
	test("b", {
		int count = 0;
		for (int i = 0; i < 1000000; ++i)
			count += 1;
		asserteq(count, 1000000);
	});
	test("c", {
		int count = 0;
		for (int i = 0; i < 1000000; ++i)
			count += 1;
		asserteq(count, 1000000);
	});
	test("d", {
		int count = 0;
		for (int i = 0; i < 1000000; ++i)
			count += 1;
		asserteq(count, 1000000);
	});
});

describe(set2, {
	test("a", {
		int count = 0;
		for (int i = 0; i < 1000000; ++i)
			count += 1;
		asserteq(count, 1000000);
	});
	test("b", {
		int count = 0;
		for (int i = 0; i < 1000000; ++i)
			count += 1;
		asserteq(count, 1000000);
	});
	test("c", {
		int count = 0;
		for (int i = 0; i < 1000000; ++i)
			count += 1;
		asserteq(count, 1000000);
	});
	test("d", {
		int count = 0;
		for (int i = 0; i < 1000000; ++i)
			count += 1;
		asserteq(count, 1000000);
	});
});

snow_main();
```

**Comment by mortie** [comment]
I just tried running the testing binary in a loop (on my desktop, which acts a bit differently from my laptop; the desktop looks like it's taking more time to ramp up). (`timetest` is from `gcc -o timetest timetest.c -DSNOW_ENABLED -I.`, where `timetest.c` contains the code posted about).

`while true; do ./timetest; done` outputs this as the first run:

```
Testing set1:
✓ Success: a: 8.80ms
✓ Success: b: 10.59ms
✓ Success: c: 8.66ms
✓ Success: d: 8.51ms
set1: Passed 4/4 tests.

Testing set2:
✓ Success: a: 7.01ms
✓ Success: b: 4.71ms
✓ Success: c: 3.84ms
✓ Success: d: 3.42ms
set2: Passed 4/4 tests.

Total: Passed 8/8 tests.Testing set1:
✓ Success: a: 1.77ms
✓ Success: b: 1.71ms
✓ Success: c: 1.71ms
✓ Success: d: 1.71ms
set1: Passed 4/4 tests.

Testing set2:
✓ Success: a: 1.71ms
✓ Success: b: 1.71ms
✓ Success: c: 1.71ms
✓ Success: d: 1.76ms
set2: Passed 4/4 tests.

Total: Passed 8/8 tests.

```

And this as the fourth run:

```
Testing set1:
✓ Success: a: 1.77ms
✓ Success: b: 1.71ms
✓ Success: c: 1.71ms
✓ Success: d: 1.71ms
set1: Passed 4/4 tests.

Testing set2:
✓ Success: a: 1.71ms
✓ Success: b: 1.71ms
✓ Success: c: 1.71ms
✓ Success: d: 1.76ms
set2: Passed 4/4 tests.

Total: Passed 8/8 tests.
```

The speed gradually improve from the first run to the fourth run, and then stay at around those same speeds until I exit the loop. This further indicates that something, or multiple things, are in a sort of power saving mode and then takes some time to exit that power saving mode once the test has started.
